config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static_pages#index"

  get "about", to: "static_pages#about"
  get "contact-us", to: "static_pages#contact"
  get "contact/:id", to: "contacts#show"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50}
  validates :phone, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :contact

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50}
  validates :password, length: { minimum: 6}
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private
  def require_logged_in_user
    unless user_signed_in?
      flash[:danger] = "restricted area, please login"
      redirect_to login_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contact
  end

  def show
  end

  def new
    @contact = Contact.new
    @action = 'create'
  end

  def edit
    @action = 'update'
  end

  def create
    @contact = current_user.contact.build(contact_params)

    if @contact.save
      redirect_to contacts_path, alert: "Contact created successfully!"
    else
      render :new, alert: "Failed to create contact!"
    end
  end

  def update
    if @contact.update(contact_params)
    #if Contact.find(params[:id]).update(contact_params)
      redirect_to contacts_path, alert: "Contact updated successfully!"
    else
      render :edit, alert: "Failed to update contact!"
    end
  end

  def destroy
    # @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path, notice: 'Contact destroyed with success.'
    # @contact.destroy
  end

  private

  def set_contact
    @contact = current_user.contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :phone)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      #redirect_to user_path(user)
      redirect_to contacts_path
    else
      flash.now[:danger] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    sign_out
    flash[:success] = "Successful logout"
    redirect_to login_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created successfully"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if current_user.update(user_params)
      flash[:success] = "Updated user"
      redirect_to contacts_url
    else
      render "edit"
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for contact, url: {action: @action}, html: {class: "nifty_form"} do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :phone %><br />
  <%= f.text_field :phone %><br /><br />

  <%= f.submit "Send", class:"btn btn-success" %>
<% end %>

app/views/contacts/edit.html.erb
<div class="jumbotron">
  <h2 class="text-center">Edit</h2>
  <%= render "form", contact: @contact %>

  <%= link_to "Cancel", contacts_path, class:"btn btn-danger" %>
</div>

app/views/contacts/index.html.erb
<div class="jumbotron">
  <h2 class="text-center">Contacts</h2>

  <table class="table responsible-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% if @contacts.empty? %>
      <tr>
        <td colspan="4" class="text-center">
          <h3>No registered contacts.</h3>
        </td>
      </tr>
      <% end %>
      
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.id  %></td>
          <td><%= contact.name %></td>
          <td><%= contact.phone %></td>
          <td><%= link_to "Show", contact_path(contact), class:"btn btn-info" %></td>
          <td><%= link_to "Edit", edit_contact_path(contact), class:"btn btn-warning" %></td>
          <td><%= link_to "Destroy", contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        </tr>
      <% end  %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Contact', new_contact_path, class:"btn btn-primary" %>

</div>

app/views/contacts/new.html.erb
<div class="jumbotron">
  <h2 class="text-center">New Contact</h2>
  <%= render 'form', contact: @contact %>

  <%= link_to 'Cancel', contacts_path, class:"btn btn-danger" %>
</div>

app/views/contacts/show.html.erb
<div class="jumbotron">
  <h2 class="text-center">Contact</h2>

  <p>Id: <%= @contact.id %></p>
  <p>Name: <%= @contact.name %></p>
  <p>Phone: <%= @contact.phone %></p>

  <%= link_to 'Back', contacts_path, class:"btn btn-primary" %>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Oops! We find <%= pluralize(object.errors.count, 'error', 'errors') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. All rights reserved.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Contact us', contact_us_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

    <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
        <% if !user_signed_in?  %>
          <li class="active">
            <%= link_to "New Account", new_user_path %>
          </li>
        <% end  %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%if !user_signed_in? %>
          <li>
              <%= link_to 'Login', login_path %>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Welcome, <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Home', current_user %>
              </li>
              <li>
                <%= link_to 'Edit', edit_user_path(current_user) %>
              </li>
              <li class="divider" role="separator"></li>
              <li>
                <%= link_to 'Logout', logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactlistror5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
         <%= message %>
        <% end %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque posuere sapien,
  nec congue felis mattis id. Pellentesque habitant morbi tristique senectus et netus et malesuada
  fames ac turpis egestas. Quisque ut fermentum odio. Proin efficitur nulla et eleifend molestie.
  Duis euismod in enim id dictum. Mauris vulputate ante sed leo posuere eleifend. Praesent ultrices at
  leo a dignissim. Sed euismod imperdiet arcu, in interdum lorem imperdiet quis. Maecenas ac porta augue.
</p>
<p>
  Nullam quis vehicula sapien, laoreet vehicula metus. Nulla sed nisl at purus egestas tincidunt.
  Aenean quis urna placerat, volutpat risus eget, fermentum nunc. Praesent viverra, diam a maximus ultrices,
  risus mauris faucibus neque, ac hendrerit massa purus id leo. Quisque efficitur ligula eget nulla hendrerit,
  quis faucibus turpis tincidunt. Praesent enim nisi, facilisis a viverra vitae, laoreet nec lacus.
  Nunc scelerisque gravida neque quis placerat. Cras accumsan euismod fringilla. Aliquam velit urna,
  lobortis sit amet metus vitae, sollicitudin tincidunt lacus. Phasellus sit amet dapibus felis.
  Sed vulputate nisi ut tortor volutpat, et vestibulum augue vestibulum. Ut ut bibendum massa, sed facilisis diam.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Curabitur malesuada diam vel arcu accumsan, non lobortis orci placerat.
  Nunc a justo et mauris pretium eleifend. Donec ultrices arcu eu turpis ultricies
  dictum eget eget massa. Donec vestibulum commodo enim, non venenatis dui feugiat eget.
  Donec ut ipsum tortor. Aliquam rhoncus mattis odio, id finibus quam lobortis eu.
  In non ex mi. Vestibulum orci ligula, varius facilisis volutpat vel, faucibus non eros.
  Nulla molestie eleifend commodo. Integer consequat vestibulum tincidunt.
</p>

<p>
  Nam arcu orci, mollis vitae lorem a, posuere volutpat nisl. In pretium non
  turpis vitae finibus. Vestibulum quis mattis mi. Quisque convallis viverra
  malesuada. Maecenas rhoncus feugiat pharetra. Aliquam consectetur sed eros id
  ornare. Aenean in rhoncus sem. Ut sed orci vestibulum, sollicitudin libero sed,
  molestie risus. Donec vel ornare libero. Nullam nec dolor libero. 
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Contact List</h1>
  <p>
    Manage your contacts anywhere!
  </p>
  <p>
    <%= link_to 'Create your account', new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-xs-12">
      <h2 class="text-center">Edit User</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
      <%= form_for current_user do |f| %>
        <%= render "form", f: f %>
        <%= f.submit 'Register', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-xs-12">
      <h2 class="text-center">Register</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
      <%= form_for @user do |f| %>
        <%= render "form", f: f %>
        <%= f.submit 'Register', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h2>Hello <%= current_user.name %></h2>
  <%= link_to "Go to contact page", contacts_path, class:"btn btn-primary" %>
</div>